.TH LDO65 "1" "11 April 2006"

.SH NAME
ldo65 \- linker for o65 object files

.SH SYNOPSIS
.B ldo65
[\fIOPTION\fR]... \fIFILE\fR...

.SH DESCRIPTION
.B ldo65
is a linker for files in the `o65' object format, formerly
.B ld65
but renamed to avoid conflicts with the
.B cc65
package (a separate product).

.SH OPTIONS
.TP
.B \-b? addr
Relocate segment 
.B ?
to 
.BR addr \&.
.B ?
must be either t, d, b or z to indicate the text, data, bss or zero
segment respectively. See the
.BR xa (1)
man page for an explanation.
.TP
.B \-o filename
Set output filename. The default is
.BR a.o65 \&.
.TP
.B \-G
Suppress writing of globals.
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of program.

.SH "SEE ALSO"
.BR file65 (1),
.BR printcbm (1),
.BR reloc65 (1),
.BR uncpk (1),
.BR dxa (1),
.BR xa (1)

.SH AUTHOR
This manual page was written by David Weinehall <tao@acc.umu.se>
and Cameron Kaiser <ckaiser@floodgap.com>.
Original xa package (C)1989-1997 Andre Fachat. Additional changes
(C)1989-2006 Andre Fachat, Jolse Maginnis, David Weinehall and
Cameron Kaiser. The current maintainer is Cameron Kaiser.

.SH WEBSITE
http://www.floodgap.com/retrotech/xa/
