.TH PRINTCBM "1" "11 April 2006"

.SH NAME
printcbm \- list a Commodore BASIC file

.SH SYNOPSIS
.B printcbm
\fIFILE\fR

.SH DESCRIPTION
.B printcbm
lists all lines of the specified Commodore BASIC program.

.SH OPTIONS
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of program.

.SH "SEE ALSO"
.BR file65 (1),
.BR ldo65 (1),
.BR reloc65 (1),
.BR uncpk (1),
.BR dxa (1),
.BR xa (1)

.SH AUTHOR
This manual page was written by David Weinehall <tao@acc.umu.se>.
Original xa package (C)1989-1997 Andre Fachat. Additional changes
(C)1989-2006 Andre Fachat, Jolse Maginnis, David Weinehall and
Cameron Kaiser. The current maintainer is Cameron Kaiser.

.SH WEBSITE
http://www.floodgap.com/retrotech/xa/
